global:
  scrape_interval: 5s  # Scrape metrics every 5 seconds
  evaluation_interval: 5s  # Evaluate rules every 5 seconds

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

